################################################################################
############################# Clean Up New Dataset #############################
################################################################################

### Load Web of Science Meta-Data
wos_metadata <- readr::read_csv("/Users/wilsonking/Desktop/wos-data/Convert_To_Dataframe_WoS.csv")

### Create Vector of Journals
journals <- c(
  
  # Das et al (2013) Top 10
  "AMERICAN ECONOMIC REVIEW",
  "ECONOMETRICA",
  "JOURNAL OF POLITICAL ECONOMY",
  "JOURNAL OF ECONOMIC THEORY",
  "QUARTERLY JOURNAL OF ECONOMICS",
  "JOURNAL OF ECONOMETRICS",
  "ECONOMETRIC THEORY",
  "REVIEW OF ECONOMIC STUDIES",
  "JOURNAL OF BUSINESS & ECONOMIC STATISTICS",
  "JOURNAL OF MONETARY ECONOMICS",
  
  # Das et al (2013) Top 11-20
  "GAMES AND ECONOMIC BEHAVIOR",
  "JOURNAL OF ECONOMIC PERSPECTIVES",
  "REVIEW OF ECONOMICS AND STATISTICS",
  "EUROPEAN ECONOMIC REVIEW",
  "INTERNATIONAL ECONOMIC REVIEW",
  "ECONOMIC THEORY",
  "JOURNAL OF HUMAN RESOURCES",
  "ECONOMIC JOURNAL",
  "JOURNAL OF PUBLIC ECONOMICS",
  "JOURNAL OF ECONOMIC LITERATURE",
  
  # Das et al (2013) Top 21-30
  "ECONOMICS LETTERS",
  "JOURNAL OF APPLIED ECONOMETRICS", 
  "JOURNAL OF ECONOMIC DYNAMICS & CONTROL", 
  "JOURNAL OF LABOR ECONOMICS",
  "JOURNAL OF ENVIRONMENTAL ECONOMICS AND MANAGEMENT",
  "RAND JOURNAL OF ECONOMICS",
  "SCANDINAVIAN JOURNAL OF ECONOMICS",
  "JOURNAL OF FINANCIAL ECONOMICS",
  "OXFORD BULLETIN OF ECONOMICS AND STATISTICS",
  "JOURNAL OF INTERNATIONAL ECONOMICS",
  
  # 
  "JOURNAL OF MATHEMATICAL ECONOMICS",
  "JOURNAL OF ECONOMIC BEHAVIOR & ORGANIZATION", 
  "SOCIAL CHOICE AND WELFARE",
  "AMERICAN JOURNAL OF AGRICULTURAL ECONOMICS",
  "INTERNATIONAL JOURNAL OF GAME THEORY",
  "ECONOMIC INQUIRY",
  "WORLD BANK ECONOMIC REVIEW",    
  "JOURNAL OF RISK AND UNCERTAINTY",
  "JOURNAL OF DEVELOPMENT ECONOMICS",
  "LAND ECONOMICS",
  "INTERNATIONAL MONETARY FUND STAFF PAPERS",
  "CANADIAN JOURNAL OF ECONOMICS",
  "PUBLIC CHOICE",
  "THEORY AND DECISION",
  "ECONOMICA",
  "JOURNAL OF URBAN ECONOMICS",
  "INTERNATIONAL JOURNAL OF INDUSTRIAL ORGANIZATION",
  "JOURNAL OF LAW ECONOMICS & ORGANIZATION", 
  "JOURNAL OF LAW & ECONOMICS", 
  "NATIONAL TAX JOURNAL",
  "JOURNAL OF INDUSTRIAL ECONOMICS",
  "JOURNAL OF ECONOMIC HISTORY",
  "OXFORD ECONOMIC PAPERS-NEW SERIES",
  "JOURNAL OF COMPARATIVE ECONOMICS",
  "WORLD DEVELOPMENT",
  "SOUTHERN ECONOMIC JOURNAL",
  "EXPLORATIONS IN ECONOMIC HISTORY",
  "ECONOMIC RECORD",
  "JOURNAL OF BANKING & FINANCE", 
  "CONTEMPORARY ECONOMIC POLICY",
  "JOURNAL OF POPULATION ECONOMICS",
  "JOURNAL OF FINANCIAL AND QUANTITATIVE ANALYSIS",
  "JOURNAL OF INSTITUTIONAL AND THEORETICAL ECONOMICS-ZEITSCHRIFT FUR DIE GESAMTE STAATSWISSENSCHAFT", 
  "APPLIED ECONOMICS",
  "SCOTTISH JOURNAL OF POLITICAL ECONOMY",
  "JOURNAL OF MACROECONOMICS",
  "REVIEW OF INCOME AND WEALTH",
  "OXFORD REVIEW OF ECONOMIC POLICY",
  "JOURNAL OF HEALTH ECONOMICS",
  "REGIONAL SCIENCE AND URBAN ECONOMICS",
  "JOURNAL OF ECONOMICS & MANAGEMENT STRATEGY", 
  "WORLD ECONOMY",
  "SMALL BUSINESS ECONOMICS",
  "ECONOMIC HISTORY REVIEW",
  "CAMBRIDGE JOURNAL OF ECONOMICS",
  "WORLD BANK RESEARCH OBSERVER",
  "ENERGY JOURNAL",
  "WELTWIRTSCHAFTLICHES ARCHIV-REVIEW OF WORLD ECONOMICS",
  "KYKLOS",
  "AUSTRALIAN ECONOMIC HISTORY REVIEW",
  "ECOLOGICAL ECONOMICS",
  "GENEVA PAPERS ON RISK AND INSURANCE THEORY",
  "REVIEW OF INDUSTRIAL ORGANIZATION",
  "JOURNAL OF TRANSPORT ECONOMICS AND POLICY",
  "ECONOMICS AND PHILOSOPHY",
  "JOURNAL OF ACCOUNTING & ECONOMICS", 
  "JOURNAL OF THE JAPANESE AND INTERNATIONAL ECONOMIES",  
  "RESOURCE AND ENERGY ECONOMICS",
  "JOURNAL OF AGRICULTURAL AND RESOURCE ECONOMICS",
  "BROOKINGS PAPERS ON ECONOMIC ACTIVITY",
  "ECONOMIC DEVELOPMENT AND CULTURAL CHANGE",
  "COMMUNIST ECONOMIES & ECONOMIC TRANSFORMATION",  
  "JOURNAL OF HOUSING ECONOMICS",
  "JOURNAL OF REGULATORY ECONOMICS",
  "MANCHESTER SCHOOL",
  "ECONOMIC MODELLING",
  "DEVELOPING ECONOMIES",
  "JOURNAL OF POLICY MODELING",
  "JOURNAL OF PRODUCTIVITY ANALYSIS",
  "CANADIAN JOURNAL OF AGRICULTURAL ECONOMICS-REVUE CANADIENNE D AGROECONOMIE",
  "AUSTRALIAN JOURNAL OF AGRICULTURAL ECONOMICS",
  "JOURNAL OF RISK AND INSURANCE",
  "JAPAN AND THE WORLD ECONOMY",
  "REVIEW OF BLACK POLITICAL ECONOMY",
  "JOURNAL OF ECONOMIC PSYCHOLOGY",
  "JOURNAL OF ECONOMIC ISSUES",
  "ECONOMICS OF EDUCATION REVIEW",
  "OPEN ECONOMIES REVIEW",
  "JOURNAL OF AGRICULTURAL ECONOMICS",
  "JOURNAL OF ECONOMIC EDUCATION",
  "EUROPEAN REVIEW OF AGRICULTURAL ECONOMICS",
  "JOURNAL OF POST KEYNESIAN ECONOMICS",
  "JOURNAL OF REAL ESTATE FINANCE AND ECONOMICS",
  "JAHRBUCHER FUR NATIONALOKONOMIE UND STATISTIK",
  "JOURNAL OF EVOLUTIONARY ECONOMICS",
  "HISTORY OF POLITICAL ECONOMY",
  "FOOD POLICY",
  "REAL ESTATE ECONOMICS",
  "HEALTH ECONOMICS",
  "CHINA ECONOMIC REVIEW",
  "POST-SOVIET AFFAIRS",
  "DEFENCE AND PEACE ECONOMICS",
  "INSURANCE MATHEMATICS & ECONOMICS",
  "REVIEW OF SOCIAL ECONOMY",
  "BULLETIN OF INDONESIAN ECONOMIC STUDIES",
  "INTERNATIONAL REVIEW OF LAW AND ECONOMICS",
  "POST-SOVIET GEOGRAPHY AND ECONOMICS",
  "ECONOMIC GEOGRAPHY",
  "ECONOMICS OF PLANNING",
  "EASTERN EUROPEAN ECONOMICS",
  "JOURNAL OF WORLD TRADE",
  "APPLIED ECONOMICS LETTERS",
  "ENERGY ECONOMICS",
  "AUSTRALIAN JOURNAL OF AGRICULTURAL AND RESOURCE ECONOMICS",
  "JOURNAL OF DEVELOPING AREAS",
  "AMERICAN JOURNAL OF ECONOMICS AND SOCIOLOGY",
  "HITOTSUBASHI JOURNAL OF ECONOMICS",
  "NEW ENGLAND ECONOMIC REVIEW",
  "DESARROLLO ECONOMICO",
  "ECONOMIC AND SOCIAL REVIEW",
  "ECONOMIC DEVELOPMENT QUARTERLY",
  "ECONOMY AND SOCIETY",
  "EKONOMICKY CASOPIS",
  "JAPANESE ECONOMY",
  "NATIONALOKONOMISK TIDSSKRIFT",
  "POLITICKA EKONOMIE",
  "PROBLEMS OF ECONOMIC TRANSITION",
  "REVUE D ETUDES COMPARATIVES EST-OUEST",
  "SOUTH AFRICAN JOURNAL OF ECONOMICS",
  "AFRICAN DEVELOPMENT REVIEW-REVUE AFRICAINE DE DEVELOPPEMENT",
  "AGRICULTURAL ECONOMICS",
  "ANNALS OF REGIONAL SCIENCE",
  "BRITISH JOURNAL OF INDUSTRIAL RELATIONS",
  "CANADIAN JOURNAL OF DEVELOPMENT STUDIES-REVUE CANADIENNE D ETUDES DU DEVELOPPEMENT",
  "REVUE CANADIENNE D ETUDES DU DEVELOPPEMENT-CANADIAN JOURNAL OF DEVELOPMENT STUDIES",
  "CANADIAN PUBLIC POLICY-ANALYSE DE POLITIQUES",
  "DE ECONOMIST", #### MISSING THIS JOURNAL
  "DEVELOPMENT AND CHANGE",
  "ECONOMIC POLICY",
  "ECONOMICS OF TRANSITION",
  "EMERGING MARKETS FINANCE AND TRADE",
  "ENVIRONMENT AND DEVELOPMENT ECONOMICS",
  "ENVIRONMENTAL & RESOURCE ECONOMICS", 
  "EUROPEAN JOURNAL OF INDUSTRIAL RELATIONS",
  "FINANCE A UVER",
  "FISCAL STUDIES",
  "GROWTH AND CHANGE",
  "HOUSING POLICY DEBATE",
  "ILR REVIEW",
  "INDUSTRIAL RELATIONS",
  "INFORMATION ECONOMICS AND POLICY",
  "INQUIRY-THE JOURNAL OF HEALTH CARE ORGANIZATION PROVISION AND FINANCING",
  "INTERNATIONAL JOURNAL OF FINANCE & ECONOMICS",
  "INTERNATIONAL REGIONAL SCIENCE REVIEW",
  "INTERNATIONAL TAX AND PUBLIC FINANCE",
  "JAPANESE ECONOMIC REVIEW",
  "JOURNAL OF AFRICAN ECONOMIES",
  "JOURNAL OF BUSINESS",
  "JOURNAL OF DEVELOPMENT STUDIES",
  "JOURNAL OF ECONOMIC GROWTH",
  "JOURNAL OF ECONOMIC SURVEYS",
  "JOURNAL OF ECONOMICS (MVEA)",
  "JOURNAL OF ECONOMICS-ZEITSCHRIFT FUR NATIONALOKONOMIE",
  "ZEITSCHRIFT FUR NATIONALOKONOMIE-JOURNAL OF ECONOMICS",
  "ZEITSCHRIFT FUR NATIONALOKONOMIE",
  "JOURNAL OF FINANCE",
  "JOURNAL OF FINANCIAL INTERMEDIATION",
  "JOURNAL OF FORECASTING",
  "JOURNAL OF INTERNATIONAL MONEY AND FINANCE",
  "JOURNAL OF LABOR RESEARCH",
  "JOURNAL OF MONEY CREDIT AND BANKING",
  "JOURNAL OF POLICY ANALYSIS AND MANAGEMENT",
  "JOURNAL OF REGIONAL SCIENCE",
  "LABOUR ECONOMICS",
  "MACROECONOMIC DYNAMICS",
  "MATHEMATICAL SOCIAL SCIENCES",
  "MONTHLY LABOR REVIEW",
  "PAPERS IN REGIONAL SCIENCE",
  "POST-COMMUNIST ECONOMIES",
  "REGIONAL STUDIES",
  "RESOURCES POLICY",
  "REVIEW OF ECONOMIC DYNAMICS",
  "REVIEW OF FINANCIAL STUDIES",
  "REVIEW OF INTERNATIONAL POLITICAL ECONOMY",
  "TELECOMMUNICATIONS POLICY",
  
  "AMERICAN ECONOMIC JOURNAL-APPLIED ECONOMICS", # New Society
  "AMERICAN ECONOMIC JOURNAL-ECONOMIC POLICY", # New Society
  "AMERICAN ECONOMIC JOURNAL-MICROECONOMICS", # New Society
  "AMERICAN ECONOMIC JOURNAL-MACROECONOMICS", # New Society
  "AMERICAN ECONOMIC REVIEW-INSIGHTS", # New Society
  "QUANTITATIVE ECONOMICS",
  "THEORETICAL ECONOMICS",
  "JOURNAL OF THE EUROPEAN ECONOMIC ASSOCIATION"
  
)


### Restrict to Only Relevant Journals
wos_metadata %<>% dplyr::filter(PublicationTitle %in% journals) %>%
  dplyr::mutate(PublicationTitle = case_when(
    PublicationTitle == "ZEITSCHRIFT FUR NATIONALOKONOMIE" | PublicationTitle == "JOURNAL OF ECONOMICS-ZEITSCHRIFT FUR NATIONALOKONOMIE" ~ "ZEITSCHRIFT FUR NATIONALOKONOMIE-JOURNAL OF ECONOMICS",
    TRUE ~ PublicationTitle))

### Remove Extraneous Files
wos_metadata %<>%
  dplyr::filter(!grepl(
    paste(c("Bibliography", "Book", "Biography", "Correction/Retraction", "Editorial",
            "Fiction", "Letter to the Editor", "News", "Review", "Undefined", "undefined"), 
          collapse = "|"), Object_types))

### Rename Variables
wos_metadata %<>%
  dplyr::rename(
    authors = Contributor,
    title = Title,
    journal = PublicationTitle,
    keywords = Keywords,
    abstract = Abstract,
    addresses = Full_Addresses,
    affiliations = Organization,
    subaffiliations = Suborganization,
    streets = Street,
    cities = City,
    states = State,
    country = Country,
    zip = `Zip Code`,
    funder = WOS_Grant_Agency,
    date = Date,
    article = Object_types) %>%
  dplyr::select(-`...1`) %>%
  dplyr::mutate(
    year = as.numeric(format(date, "%Y")))

### Remove Publications from Before 1995
wos_metadata %<>%
  dplyr::filter(as.Date(date) >= "1995-01-01" & as.Date(date) < "2025-01-01")

### Fix HTML
wos_metadata %<>% dplyr::mutate(title = xutils::html_decode(title))

### Standardize Cases in Titles
wos_metadata %<>%
  dplyr::mutate(
    title = case_when(
      !is_uppercase(title) ~ title,
      is_uppercase(title) ~ str_to_title(title))) %>%
  dplyr::mutate(
    title = gsub("\\b(Us)\\b", "US", title, perl = TRUE),
    title = gsub("\\b(Uk)\\b", "UK", title, perl = TRUE),
    title = gsub("\\b(Uae)\\b", "UAE", title, perl = TRUE),
    title = gsub("\\b(Nhs)\\b", "NHS", title, perl = TRUE),
    title = gsub("\\b(Tanf)\\b", "TANF", title, perl = TRUE)) %>%
  dplyr::mutate(
    title = tools::toTitleCase(title))

### Create Empty Variable for Country Assignment
wos_metadata$topic <- NA

### Assign Countries
set.seed(62361)
wos_metadata$topic <- mapply(assign_country, title = wos_metadata$title, abstract = wos_metadata$abstract)
# save(wos_metadata, file = paste0(data, "wos_assigned_jpal_ipa.RData"))

### Create RCT Strings
experiment_string <- paste(
  c("field[- ]?experiment", "randomi[sz]ed (controlled )?(trial|experiment|evaluation|impact evaluation)",
    "clinical trial"," ?rcts? ?"), collapse = "|")

### Create RDD Strings
rdd_string <- paste(
  c("regression discontinuit(y|ies)", "difference[- ]in discontinuit(y|ies)", "RD design",
    "(discontinuit(y|ies) )?design", "spatial RD"), collapse = "|")

### Create Diff-in-Diff Strings
did_string <- paste(
  c("two way fixed effect(s)?", "difference[- ]in[- ]difference",
    "diff[- ]in[- ]diff", "triple diff"), collapse = "|")

### Create Lab Experiment Strings
lab_string <- paste(
  c("lab(oratory)? experiment", "lab(oratory)? study"), collapse = "|")

### Create Topic Indicators
wos_metadata %<>%
  dplyr::mutate(
    rct = as.numeric(
      grepl(experiment_string, title, ignore.case = TRUE) |
        grepl(experiment_string, abstract, ignore.case = TRUE) |
        grepl(experiment_string, keywords, ignore.case = TRUE)
    ),
    rdd = as.numeric(
      grepl(rdd_string, title, ignore.case = TRUE) |
        grepl(rdd_string, abstract, ignore.case = TRUE) |
        grepl(rdd_string, keywords, ignore.case = TRUE)
    ),
    did = as.numeric(
      grepl(did_string, title, ignore.case = TRUE) |
        grepl(did_string, abstract, ignore.case = TRUE) |
        grepl(did_string, keywords, ignore.case = TRUE)
    ),
    lab = as.numeric(
      grepl(lab_string, title, ignore.case = TRUE) |
        grepl(lab_string, abstract, ignore.case = TRUE) |
        grepl(lab_string, keywords, ignore.case = TRUE)
    )
  )




